include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: true
    sort_pub_dependencies: true
    directives_ordering: true
    unnecessary_parenthesis: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    one_member_abstracts: false
    prefer_const_declarations: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
