arb-dir: lib/src/localizations/translations
output-dir: lib/src/localizations/translations/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: en
synthetic-package: false
